**y=x^2**

In [ ]:
import torch

In [ ]:
x=torch.tensor(2.0,requires_grad=True)

In [ ]:
x

tensor(2., requires_grad=True)

In [ ]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(4.)

In [ ]:
lst=[[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input=torch.tensor(lst,requires_grad=True)
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [ ]:
y=torch_input**3+torch_input**2+torch_input**1
y

tensor([[ 14.,  39.,   3.],
        [ 84., 155.,  39.],
        [399., 258.,  84.]], grad_fn=<AddBackward0>)

In [ ]:
z=y.sum()
z

tensor(1075., grad_fn=<SumBackward0>)

In [ ]:
z.backward()

In [ ]:
torch_input.grad

tensor([[ 17.,  34.,   6.],
        [ 57.,  86.,  34.],
        [162., 121.,  57.]])