In [ ]:
import torch

In [ ]:
torch.__version__

'2.3.1+cu121'

In [ ]:
import numpy as np


In [ ]:
lx=[5,4,7]
arr=np.array(lx)

In [ ]:
arr.dtype

dtype('int64')

**Convert Numpy to Pytorch Tensors** **bold text**

In [ ]:
tensors=torch.from_numpy(arr)
tensors

tensor([5, 4, 7])

In [ ]:
tensors.dtype

torch.int64

In [ ]:
#Indexing is similar to numpy
tensors[:2]

tensor([5, 4])

In [ ]:
#Disadvantage of from_numpy. The tensor and array uses the same memory location
tensors[2]=101

In [ ]:
tensors

tensor([  5,   4, 101])

In [ ]:
arr

array([  5,   4, 101])

In [ ]:
#prevent this by using the torch.tensor
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([  5,   4, 101])

In [ ]:
tensor_arr[2]=125
print(tensor_arr)
print(arr)

tensor([  5,   4, 125])
[  5   4 101]


In [ ]:
#zeroes and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [ ]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [ ]:
a=torch.tensor(np.arange(0,15).reshape(5,3))
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

**Arithmetic operations**

In [ ]:
a=torch.tensor([3,4,5],dtype=torch.float)
b=torch.tensor([4,5,6],dtype=torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [ ]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [ ]:
c=torch.ones(3)
c

tensor([1., 1., 1.])

In [ ]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [ ]:
c

tensor([ 7.,  9., 11.])

In [ ]:
torch.add(a,b).sum()

tensor(27.)

**Dot product and Multiplication operation**

In [ ]:
x=torch.tensor([3,4,5],dtype=torch.float)
y=torch.tensor([4,5,6],dtype=torch.float)
print(x)
print(y)

tensor([3., 4., 5.])
tensor([4., 5., 6.])


In [ ]:
x.mul(y)

tensor([12., 20., 30.])

In [ ]:
x.dot(y)

tensor(62.)

**Matrix multiplication**

In [ ]:
x=torch.tensor([[1,2,3],[4,5,0],[8,7,4]],dtype=torch.float)
y=torch.tensor([[1,2,3],[4,5,6],[8,7,4]],dtype=torch.float)
print(x)
print(y)

tensor([[1., 2., 3.],
        [4., 5., 0.],
        [8., 7., 4.]])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [8., 7., 4.]])


In [ ]:
torch.matmul(x,y)

tensor([[33., 33., 27.],
        [24., 33., 42.],
        [68., 79., 82.]])

In [ ]:
torch.mm(x,y)

tensor([[33., 33., 27.],
        [24., 33., 42.],
        [68., 79., 82.]])

In [ ]:
x@y

tensor([[33., 33., 27.],
        [24., 33., 42.],
        [68., 79., 82.]])